---
- name: Downloading of httpd package
  hosts: all
  become: true
  gather_facts: no
  tasks:
  - name: Installing of httpd package
    yum: 
     name: httpd
     state: installed
  - name: Restarting of httpd package
    service:
      name: httpd      
      state: started
  - name: copy the index.html file from src to dest
    copy:
     src: /var/www/html/index.html
     dest: /var/www/html/       
