---
- name: Installing of packages using when condition
  hosts: all
  become: true
  gather_facts: yes 
  tasks:
  - name: Installing of apache2 packages on ubuntu
    apt:
     name: apache2
     state: present
    when: ansible_os_family == "Debian"
  
  - name: Installing of httpd packages on Linux
    yum:
     name: httpd
     state: installed
    when: ansible_os_family == "RedHat"

  - name: Start of httpd packages on Linux
    service:
     name: httpd
     state: started
     enabled: yes
    when: ansible_os_family == "RedHat"
 
  - name: Start of apache2 packages on Ubuntu
    service:
     name: apache2
     state: started
    when: ansible_os_family == "Debian"   

  - name: copying the index.html from controller to nodes
    copy:
     src: /home/ansadmin/playbooks/index.html
     dest: /var/www/html/     

